version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "9090:8080"
    container_name: jenkins
    volumes:
      - /Users/venukannuri/development/docker/volumes/jenkins_home:/var/jenkins_home jenkins/jenkins

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /Users/venukannuri/development/docker/volumes/sonarqube_data:/opt/sonarqube/data
      - /Users/venukannuri/development/docker/volumes/sonarqube_extensions:/opt/sonarqube/extensions
      - /Users/venukannuri/development/docker/volumes/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9092:9000"
  db:
    image: postgres:9.6
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /Users/venukannuri/development/docker/volumes/postgres_home:/var/lib/postgresql
      - /Users/venukannuri/development/docker/volumes/postgres_data:/var/lib/postgresql/data


